= AsciiDoc cheat sheet focused on the web

// NOTE: The empty anchors such as `[[sectnumlevels]]` to make these terms searchable in Dash

== Structure

=== Document header

....
= Main Header <1>
Jakub Holý <holyjak@example.com> <2>
v1.2.3, 2021-09-29: my optional revision remark <3>
:author: Jakub Holý <4>
:email: <holyjak@example.com> <5>
:revnumber: 1.2.3 <6>
:revdate: 2021-09-29 <7>
:revremark: my optional revision remark <8>
<9>
....
<1> Optional document title
<2> Optional author line
<3> Optional revision info (version, date, remark - each optional); can _only_ be used if there is an author line. See https://docs.asciidoctor.org/asciidoc/latest/document/revision-information/[revision Information]
<4> An alternative way to set the optional author name; see https://docs.asciidoctor.org/asciidoc/latest/document/author-information/[author info] docs
<5> An alternative way to set the optional author email
<6> An alternative way to set the optional revision number (no 'v' prefix)
<7> An alternative way to set the optional revision date
<8> An alternative way to set the optional revision remark
<9> Blank line that ends the document header

== Attributes

=== Document attributes

Configure and turn on/off built-in features, built-in asset locations, set "variables" for reuse elsewhere in the document. See https://docs.asciidoctor.org/asciidoc/latest/attributes/document-attributes/#what-does-defining-a-document-attribute-mean[rules for values].

Most document attributes are set right under the main header / document title, some can be (re)set anywhere (e.g. `sectnums`):

....
= Document Title
:sectnums: // turn on a boolean attr
:!sectnums: // turn it off
:imagesdir: ./my/img/subdir/ // built-in attr. with a value
:my-homepage: https://holyjak.cz // a custom attribute

A reference to an attribute such as link:{my-homepage}[my www] 
will be replaced with the value automatically.
....

See https://docs.asciidoctor.org/asciidoc/latest/attributes/document-attributes-ref/[Document Attributes Reference] for a full list.

=== Element attributes

Override the built-in settings of blocks, macros, or inline elements and add custom settings (e.g. id, CSS classes) by using attribute lists. Attributes are _comma-separated_ and can be _positional_ (come first) and/or _named_:

....
image:path[Image alt text,200,150]
image:path["Image alt text",height=150,width=200]
....

* Values can be enclosed in double `"` or single `'` _quotes_; only inside `'...'` do normal substitutions (basic formatting etc.) apply
* Document _attribute references_ such as `{some-attr}` are replaced with their values

For _blocks_ and block elements, put the attributes on the preceding line:

....
[square]
* one
* two
....

== Section Titles

=== Section Titles

Mark titles with `=`:

....
= Document title (h1)
== Level 1 (h2)
...
====== Level 5 (h6)
....

To auto-number sections, turn on [[sectnumlevels]][[sectnums]]`sectnums`: 

....
:sectnums:
:sectnumlevels: 2 <1>
== Numbered section
:!sectnums:
== Unnumbered again
....
<1> Number section headings at levels 1 and 2. Optional, default: levels 1-3

To use a heading where sections are not allowed (e.g. inside a block), set the [[discrete]]`[discrete]` attribute.

== Paragraphs

=== Paragraphs

+++<table><tr style="vertical-align:top"><td>+++

.Paragraphs' source
....
include::includes-examples.adoc[tag=paragraphs]
....
+++</td><td>+++

.Paragraphs rendered
--
include::includes-examples.adoc[tag=paragraphs]
--

+++</td></tr></table>+++

To pass inline text through unchanged to HTML, wrap with three `+`:

....
+++<div id=x>+++
....

=== Assign id and CSS class(es) (a.k.a. roles) to inline text

Roles = CSS classes can be assigned similarly as ID, 
see link:++#//dash_ref/Category/Links+and+anchors++[Links and anchors] below. +
Ex.: `+[.class.another]#some text#+`.

== Text Formatting

=== Text Formatting

[%autowidth]
|===
| [[bold]]*bold* | `+*bold*+`
| [[italic]]_italic_ | `+_italic_+`
| *_both_* | `+*_both_*+`
| [[monospace]]`mon**os**pace` | `+++`mon**os**pace`+++` - formatting applies
| [[literal]]`+li**t**eral monospace+` | $$`+li**t**eral+`$$ - add `+` to suppress formatting etc.
| **b**ol__d__ c``od``e | double to stop mid-word: `+++**b**ol__d__ c``od``e+++`
| [[highlight]]#highlight# | `+#highlight#+`
| [[underline]][.underline]#underline# | `+[.underline]#underline#+`
| [[line-through]][.line-through]#line-through# | `+[.line-through]#line-through#+`
| [.my-class]#txt# | assign arbitrary css class: `+[.my-class]#txt#+`
| [[superscript]]^super^script | `+^super^script+`
| [[subscript]]~sub~script | `+~sub~script+`
| [[quotes]]"`double curved quotes`" | pass:["`double curved quotes`"]
| '`single curved quotes`' | pass:['`single curved quotes`']
| [[apostrophes]]apostrophes`' vs x' | pass:[apostrophes`' vs x']
|===

== Blocks and admonitions

=== Admonitions

+++<table><tr style="vertical-align:top"><td>+++

.Admonitions' source
....
include::includes-examples.adoc[tag=admonitions]
....

+++</td><td>+++

.Admonitions rendered
--
include::includes-examples.adoc[tag=admonitions]
--

+++</td></tr></table>+++

All admonitions: [[NOTE]]NOTE, [[TIP]]TIP, [[IMPORTANT]]IMPORTANT, [[WARNING]]WARNING, [[CAUTION]]CAUTION.

=== Blocks

.General structure of a block:
....
.Optional title
[optional attributes]
<separator (2 or 4 characters)>
<content>
<separator>
....

[%autowidth]
|===
| block type | separator, attributes, comments

| [[source_code]]source code | `----`; attributes: `[source,ruby]`
| source code (markdown) 
| [[pass]]`pass:[```&lt;language&gt; ... ```]`
| [[sidebar]]sidebar | `+++****+++`
| [[example]]example | `====`; expandable^1^: `[%collapsible]`, closable: `[%collapsible%open]`
| [[quote]]quote   | `+++____+++`; attributes: `[quote, Author, Source]`^2^
| quote, alternative | "Text in quotes", on a new line `-- Author, Source`
| [[open_block]]open^1^    | `--` An anonymous container; can masquerade as any other by naming it: `+[source\|...]+`
| [[passthrough]]passthrough | `pass:[++++]`, pass content unchanged; e.g. to include HTML  
|===

1. The expandable example block and open block may contain other blocks
2. Wrap the quote source in `'` to enable basic AsciiDoc such as links

*Common block attributes*: [[id]]link:https://docs.asciidoctor.org/asciidoc/latest/attributes/ids/#anchor[`id`] 
(or `+#+`), [[role]]link:https://docs.asciidoctor.org/asciidoc/latest/attributes/role/[`role`] (or `.`) = css class, 
[[options]][[opts]]link:https://docs.asciidoctor.org/asciidoc/latest/attributes/options/[`options`] 
(or `opts` for short or the repeatable `%<name>`). 
Example of all, using the shorthand forms: `+[quote#roads.movie.class2%fakeOpt, Dr. Emmett Brown]+`.

=== Source code listing

....
include::includes-examples.adoc[tag=codelisting]
....

When including regions by tags, mark them using line comments like these:

....
# tag::mytag[]
...
# end::mytag[]
....

See https://docs.asciidoctor.org/asciidoc/latest/directives/include-with-indent/[include-with-indent], https://docs.asciidoctor.org/asciidoc/latest/directives/include-tagged-regions/[include-tagged-regions] and https://docs.asciidoctor.org/asciidoc/latest/directives/include-lines/[include-lines].

== Lists

=== Lists

.(Un)ordered lists source
....
include::includes-examples.adoc[tag=lists]
....

.(Un)ordered lists rendered
// must be open block b/c it contains another block
--
include::includes-examples.adoc[tag=lists]
--

+++<table><tr style="vertical-align:top"><td>+++

.Other list types source
....
include::includes-examples.adoc[tag=lists-other-types]
....

+++</td><td>+++

.Other list types rendered
====
include::includes-examples.adoc[tag=lists-other-types]
====

+++</td></tr></table>+++

== Links and anchors

=== Anchors

*Block or a section* heading: use a block anchor `+[[myid]]+` or the shorthand form `+[#myid]+` in the first position of the block attribute list.

*Inline*, on quoted text using _either_ formatting marks such as `*` _or_ put `#` around the text:
`+[#inline_target]#targeted# txt+`. Or just insert an empty anchor: `+[[empty-anchor]]not inside+`.

Anchors can be used anywhere https://docs.asciidoctor.org/asciidoc/latest/subs/#substitution-groups[where macro substitution applies].

[#heading-anchor]
=== Links

*Link to an anchor* via `+<<myid>>+`, which will use the target text as the label (only works for headings), or `+<<myid,custom label>>+`. You can also link directly to a section heading using its text: `+<<Links>>+`.

[%autowidth]
|===
| *Links to anchors:* |
| `+<<heading-anchor>>+`, `+<<inline_target>>+` | <<heading-anchor>>, <<inline_target>>
| `+<<heading-anchor,my label>>+` | <<heading-anchor,my label>>
| `+<<Links>>+` - heading text | <<Links>>
| *External links:* |
| `+http://xy.z+` | http://xy.z
| `+http://xy.z[label]+` | http://xy.z[label]
| `+link:/some/path[path only]+` | link:/some/path[path only]
|===

Beware: Some URLs look like formatting and confuse the parser. To fix, wrap like this `$$link:++the-url++$$` or assign it to an attribute and use that.

https://docs.asciidoctor.org/asciidoc/latest/macros/link-macro-ref/[Supported attributes]: id, role (= CSS class), title, window (or append `^` to the label for _blank), opts. 

== Images

=== Images

Block image: `+image::<path|url>[<attributes>]+` (prepend a `.block title` line for a caption)

Inline image: same as block image, but single `:`

Positional attributes: `[alt, width, height]`. W/h are numbers in px or %: 150 or 50%.

Named attributes (^1^ applies only to block images): 

* https://docs.asciidoctor.org/asciidoc/latest/macros/image-position/[Positioning]: align^1^=left|center|right, float=left|right (adds CSS style with `float`), role (built-in classes: left, right, text-left, text-right, text-center; note: `.role` shorthand not supported)
* Add a frame: `role="thumb"` (as thumbnail)
* link

Note: The document attribute [[imagesdir]]`imagesdir` (default: empty) is automatically prepended to all relative paths.

== Tables

=== Tables

.Table source
....
include::includes-examples.adoc[tag=tables]
....

.Table rendered
====
include::includes-examples.adoc[tag=tables]
====

* Make first line header by appending an empty line
* Options include [[autowidth]]`%autowidth`
* See https://docs.asciidoctor.org/asciidoc/latest/tables/add-columns/[sizing, alignment via cols], https://docs.asciidoctor.org/asciidoc/latest/tables/data-format/[CSV data] etc.

== Extra

=== Extra

* [[comment]]Comments: `// comment here`
* [[macro]]Macros: block (`::`) or inline (`:`): `+<macro name>::<target>[<attrs>]+`
* [[escape]]https://docs.asciidoctor.org/asciidoc/latest/pass/pass-macro/[Escape] by prepending `+\+` or wrapping with `pass:[+++...+++]` or use the pass inline macro `+++pass:[whatever]+++` 
* [[hr]]`+'''+` => `<hr>`
* [[footnote]]Footnote: `footnote:<optional id>[text]`
* [[appendix]]Appendix: prepend a line with `[appendix]`
* [[icons]]How to https://docs.asciidoctor.org/asciidoc/latest/macros/icons/[enable icons] for admonitions, callouts, and the icon macro
* [[substitutions]]https://docs.asciidoctor.org/asciidoc/latest/subs/substitutions/[Substitutions, where they apply]; types: special char. (<, >, & -> `+&lt;+` etc.), quotes, attribute `{references}`, replacements (e.g. `+(R), &euro;, &#x2020;+` => (R), &euro;, &#x2020;; Unicode escape sequence yet unsupported), macros, post-replacements (the line break char. `+`)
